### ISSUE TITLE
Misspelled /redux/Posts

### ISSUE THREAD

**Issue by radu-m** [atsao/react-redux-boilerplate#17]
The file name starts with capital P and it is referred to as ../redux/posts in the source, resulting in the following error

`Error: no such file or directory
    at MemoryFileSystem.readFileSync (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.(anonymous function) [as readFile] (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/memory-fs/lib/MemoryFileSystem.js:300:34)
    at app.use (/media/bigotin/the_gimp/couch_node_react/react-redux-three/server/config/dev.js:25:31)
    at Layer.handle [as handle_request] (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:317:13)
    at /media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:284:7
    at param (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:354:14)
    at param (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:410:3)
    at next (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:275:10)
    at middleware (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/webpack-hot-middleware/middleware.js:26:48)
    at Layer.handle [as handle_request] (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:317:13)
    at /media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:335:12)
    at next (/media/bigotin/the_gimp/couch_node_react/react-redux-three/node_modules/express/lib/router/index.js:275:10)`

**Comment by atsao** [comment]
Thanks @radu-m! Addressed in #18
